// Copyright (C) 2023-2026 Òscar Casajuana Alonso

package grabber

import (
	"encoding/json"
	"fmt"
	"math/rand/v2"
	"net/url"
	"regexp"
	"strconv"
	"strings"

	"github.com/PuerkitoBio/goquery"
	"github.com/elboletaire/manga-downloader/http"
)

// Jestful is a grabber for jestful.net. Both the series page (chapter list)
// and the reader page (page images) only render a "Loading...." placeholder
// server-side: the real content is fetched client-side via two endpoints
// matched purely by their extension (the random-looking path segment in
// front of the extension is generated by the site's own JS but is never
// validated server-side, it's just cache-busting for the browser):
//
//   - "/{random}.lst?manga={slug}" returns the full chapters list as JSON
//     (id, chapter number, ...) - no pagination needed, the whole series
//     comes back in one response.
//   - "/{random}.iog?cid={chapterId}" returns an HTML fragment with the
//     page <img> tags for that chapter.
//
// Both endpoints 403 without a Referer header pointing at the site.
type Jestful struct {
	*Grabber
	title string
}

func NewJestful(g *Grabber) *Jestful {
	return &Jestful{Grabber: g}
}

// JestfulChapter represents a Jestful Chapter
type JestfulChapter struct {
	Chapter
	// ID is the chapter id, used as the "cid" query param to fetch its pages
	ID string
	// Number is the chapter number as it appears in the reader page URL
	// (e.g. "148.2"), kept as a string since it may have a trailing ".0"-less
	// decimal that doesn't round-trip cleanly through float formatting
	Slug string
}

// Test returns true if the URL is a jestful.net URL
func (m *Jestful) Test() (bool, error) {
	re := regexp.MustCompile(`jestful\.net`)
	return re.MatchString(m.URL), nil
}

// FetchTitle fetches and returns the manga title
func (m *Jestful) FetchTitle() (string, error) {
	if m.title != "" {
		return m.title, nil
	}

	body, err := http.Get(http.RequestParams{
		URL: m.URL,
	})
	if err != nil {
		return "", err
	}
	defer body.Close()

	doc, err := goquery.NewDocumentFromReader(body)
	if err != nil {
		return "", err
	}

	// the series title only appears, properly cased, as the last breadcrumb
	// item (the visible <h3> on the page is all-caps)
	m.title = sanitizeTitle(doc.Find(`ol.breadcrumb li:last-child span[itemprop="name"]`).First().Text())

	return m.title, nil
}

// FetchChapters returns the chapters of the manga
func (m Jestful) FetchChapters() (Filterables, []error) {
	slug, err := m.slug()
	if err != nil {
		return nil, []error{err}
	}

	uri := m.BaseUrl() + "/" + randomString(20) + ".lst?" + url.Values{"manga": {slug}}.Encode()
	body, err := http.GetText(http.RequestParams{
		URL:     uri,
		Referer: m.URL,
	})
	if err != nil {
		return nil, []error{err}
	}

	var feed []jestfulChapterEntry
	if err = json.Unmarshal([]byte(body), &feed); err != nil {
		return nil, []error{err}
	}

	chapters := make(Filterables, 0, len(feed))
	for _, c := range feed {
		number, err := strconv.ParseFloat(c.Chapter, 64)
		if err != nil {
			continue
		}

		title := strings.TrimSpace(c.Name)
		if title == "" {
			title = "Chapter " + c.Chapter
		}

		chapters = append(chapters, &JestfulChapter{
			Chapter{
				Number: number,
				Title:  title,
			},
			c.ID,
			c.Chapter,
		})
	}

	return chapters, nil
}

// FetchChapter fetches a chapter and its pages
func (m Jestful) FetchChapter(f Filterable) (*Chapter, error) {
	jchap, ok := f.(*JestfulChapter)
	if !ok {
		return nil, fmt.Errorf("invalid chapter type %T", f)
	}

	slug, err := m.slug()
	if err != nil {
		return nil, err
	}

	readerUri, _ := url.JoinPath(m.BaseUrl(), fmt.Sprintf("bsaq-%s-chapter-%s.html", slug, jchap.Slug))

	uri := m.BaseUrl() + "/" + randomString(20) + ".iog?" + url.Values{"cid": {jchap.ID}}.Encode()
	body, err := http.Get(http.RequestParams{
		URL:     uri,
		Referer: readerUri,
	})
	if err != nil {
		return nil, err
	}
	defer body.Close()

	doc, err := goquery.NewDocumentFromReader(body)
	if err != nil {
		return nil, err
	}

	chapter := &Chapter{
		Title:    f.GetTitle(),
		Number:   f.GetNumber(),
		Language: "en",
	}

	doc.Find("img.chapter-img").Each(func(i int, s *goquery.Selection) {
		src := strings.TrimSpace(s.AttrOr("src", ""))
		if src == "" {
			return
		}
		chapter.Pages = append(chapter.Pages, Page{
			Number: int64(i + 1),
			URL:    src,
		})
	})
	chapter.PagesCount = int64(len(chapter.Pages))

	return chapter, nil
}

// slug returns the manga slug from the URL (i.e.
// "jitsu-wa-ore-saikyou-deshita" for
// https://jestful.net/hwms-jitsu-wa-ore-saikyou-deshita.html)
func (m Jestful) slug() (string, error) {
	re := regexp.MustCompile(`hwms-([^/]+)\.html`)
	matches := re.FindStringSubmatch(m.URL)
	if len(matches) != 2 {
		return "", fmt.Errorf("could not find manga slug in url %s", m.URL)
	}
	return matches[1], nil
}

// jestfulChapterEntry is a single entry of the ".lst" chapters list JSON feed
type jestfulChapterEntry struct {
	ID      string `json:"id"`
	Chapter string `json:"chapter"`
	Name    string `json:"name"`
}

// randomString returns a random lowercase alphanumeric string of length n,
// mimicking the random path segment jestful.net's own JS generates before
// its ".lst"/".iog" endpoints
func randomString(n int) string {
	const charset = "abcdefghijklmnopqrstuvwxyz0123456789"
	b := make([]byte, n)
	for i := range b {
		b[i] = charset[rand.IntN(len(charset))]
	}
	return string(b)
}
